name = "Cozy Creations"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59e43c6d9aa360d7eb3cc6897a5ea4b535e3a938a49a8a1b4ef7dfcc8fe69ef5"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"
